---
- name: Check if SecureSHell is dotfile
  ansible.builtin.stat:
    path: "{{ home_dir }}/.ssh/config"
  register: config_stat

- name: Configure Secure Shell
  ansible.builtin.command:
    cmd: "stow ssh"
    chdir: "{{ dotfiles }}"
  when: (config_stat.stat.islnk is defined and config_stat.stat.islnk) or config_stat.stat.exists == False
  changed_when: False

