---
## TODO:
## - Bash setup (aliases)
## - Git configuratio  (user \ email)

- hosts: localhost
  user: root
  collections:
    - ansible.builtin
  
  pre_tasks:
    - block:
      - name: Set Basic Facts
        ansible.builtin.set_fact:
          home_dir: "{{ ansible_env.HOME }}"
          dotfiles: "{{ ansible_env.HOME }}/dotfiles"
          username: "{{ ansible_env.USER }}"
          uid: "{{ ansible_user_uid }}"
          os: "{{ ansible_distribution }}"
          build_dir: "{{ ansible_env.HOME }}/builds"

      - name: Show Facts
        vars:
          msg: |
            Linux    :  {{ os }}
            Home     :  {{ home_dir }}
            dotfiles :  {{ dotfiles }}
        ansible.builtin.debug:
          msg: "{{ msg.split('\n') }}"

      - name: Set Hostname
        ansible.builtin.hostname:
          name: zra-hbennett-l1.spirentcom.com
      
      - name: Basic Directories
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory
        loop:
          - "{{ home_dir }}/bin"
          - "{{ home_dir }}/.bashrc.d"
      tags: always

    - name: Update Sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/hbennett
        create: yes
        line: "hbennett ALL=(ALL) NOPASSWD: ALL"
      become: yes
      become_user: root

  roles:
    - role: base
    - role: development
    - role: git
    - role: arch_yay
    - role: ssh_agent
    - role: dotfiles
    - role: ghostty
    - role: docker
    - role: lazydocker
    - role: lazygit
    # - role: neovim
    # - role: onelogin
    # - role: ssh_client
    # - role: ssh_server
    # - role: shells_general
    # - role: shells_bash
    # - role: starship
    # - role: system_settings
    # - role: ydotool

  tasks:

